version: '3.8'

services:
  myapp:
    build:
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: "mongodb"
    ports:
      - "27017:27017"

  mongo-test:
    image: mongo:6.0
    container_name: "mongodb"
    ports:
      - "27018:27017"

  nats:
    image: nats:2.9.23
    ports:
      - "4222:4222"

  nats-tests:
    image: nats:2.9.23
    ports:
      - "4444:4222"
