version: '3.8'

services:
  myapp:
    build:
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
