version: '3.8'

services:
  myapp:
    build:
      dockerfile: Dockerfile
    container_name: "app"
    image: "rysakovb/test:latest"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: "mongo"
    ports:
      - "27070:27017"
