version: '3.8'

services:
  app-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app-test"
    ports:
      - "8080:8080"
    depends_on:
      - mongo-test
      - nats-tests

  mongo-test:
    image: mongo:6.0
    container_name: "mongodb-test"
    ports:
      - "27018:27017"

  nats-tests:
    image: nats:2.9.23
    container_name: "nats-test"
    ports:
      - "4444:4222"
