version: '3.8'

services:
  mongo-test:
    image: mongo:6.0
    container_name: "mongodb-test"
    ports:
      - "27018:27017"

  nats-tests:
    image: nats:2.9.23
    container_name: "nats-test"
    ports:
      - "4444:4222"

  redis:
    image: redis:alpine3.18
    container_name: "redis-test"
    ports:
      - "6479:6379"
