nats:
  uri: nats://localhost:4222

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/main
    redis:
      port: 6379

  kafka:
    bootstrap-servers: http://localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: my-group
      auto-offset-reset: earliest

grpc:
  server:
    port: 9090
