name: Build

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MongoDB container
        run: |
          docker run -d --name mongo -p 27017:27017 \
            -e MONGO_INITDB_DATABASE=main \
            mongo:6.0

      - name: Start MongoDB test-container
        run: |
          docker run -d --name mongo-test -p 27018:27017 \
            -e MONGO_INITDB_DATABASE=testDB \
            mongo:6.0    

      - name: Start NATS container
        run: docker run -d --name nats -p 4222:4222 nats:latest

      - name: Start NATS test-container
        run: docker run -d --name nats-test -p 4444:4222 nats:latest

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and run checks
        run: ./gradlew build
